/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PaymentReturnRouteImport } from './routes/payment-return'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminEnrolmentsRouteImport } from './routes/_authenticated/admin.enrolments'
import { Route as AuthenticatedAdminInstalmentsRouteImport } from './routes/_authenticated/admin.instalments'
import { Route as AuthenticatedAdminReferralsRouteImport } from './routes/_authenticated/admin.referrals'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as ApiPublicFlutterwaveWebhookRouteImport } from './routes/api/public/flutterwave-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment-return',
  path: '/payment-return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEnrolmentsRoute =
  AuthenticatedAdminEnrolmentsRouteImport.update({
    id: '/enrolments',
    path: '/enrolments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInstalmentsRoute =
  AuthenticatedAdminInstalmentsRouteImport.update({
    id: '/instalments',
    path: '/instalments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReferralsRoute =
  AuthenticatedAdminReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicFlutterwaveWebhookRoute =
  ApiPublicFlutterwaveWebhookRouteImport.update({
    id: '/api/public/flutterwave-webhook',
    path: '/api/public/flutterwave-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/payment-return': typeof PaymentReturnRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/enrolments': typeof AuthenticatedAdminEnrolmentsRoute
  '/admin/instalments': typeof AuthenticatedAdminInstalmentsRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/payment-return': typeof PaymentReturnRoute
  '/admin/enrolments': typeof AuthenticatedAdminEnrolmentsRoute
  '/admin/instalments': typeof AuthenticatedAdminInstalmentsRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/payment-return': typeof PaymentReturnRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/enrolments': typeof AuthenticatedAdminEnrolmentsRoute
  '/_authenticated/admin/instalments': typeof AuthenticatedAdminInstalmentsRoute
  '/_authenticated/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/payment-return'
    | '/admin'
    | '/admin/enrolments'
    | '/admin/instalments'
    | '/admin/referrals'
    | '/admin/team'
    | '/api/public/flutterwave-webhook'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/payment-return'
    | '/admin/enrolments'
    | '/admin/instalments'
    | '/admin/referrals'
    | '/admin/team'
    | '/api/public/flutterwave-webhook'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/payment-return'
    | '/_authenticated/admin'
    | '/_authenticated/admin/enrolments'
    | '/_authenticated/admin/instalments'
    | '/_authenticated/admin/referrals'
    | '/_authenticated/admin/team'
    | '/api/public/flutterwave-webhook'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  ApiPublicFlutterwaveWebhookRoute: typeof ApiPublicFlutterwaveWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-return': {
      id: '/payment-return'
      path: '/payment-return'
      fullPath: '/payment-return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enrolments': {
      id: '/_authenticated/admin/enrolments'
      path: '/enrolments'
      fullPath: '/admin/enrolments'
      preLoaderRoute: typeof AuthenticatedAdminEnrolmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/instalments': {
      id: '/_authenticated/admin/instalments'
      path: '/instalments'
      fullPath: '/admin/instalments'
      preLoaderRoute: typeof AuthenticatedAdminInstalmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/referrals': {
      id: '/_authenticated/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AuthenticatedAdminReferralsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/flutterwave-webhook': {
      id: '/api/public/flutterwave-webhook'
      path: '/api/public/flutterwave-webhook'
      fullPath: '/api/public/flutterwave-webhook'
      preLoaderRoute: typeof ApiPublicFlutterwaveWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEnrolmentsRoute: typeof AuthenticatedAdminEnrolmentsRoute
  AuthenticatedAdminInstalmentsRoute: typeof AuthenticatedAdminInstalmentsRoute
  AuthenticatedAdminReferralsRoute: typeof AuthenticatedAdminReferralsRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEnrolmentsRoute: AuthenticatedAdminEnrolmentsRoute,
  AuthenticatedAdminInstalmentsRoute: AuthenticatedAdminInstalmentsRoute,
  AuthenticatedAdminReferralsRoute: AuthenticatedAdminReferralsRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  ApiPublicFlutterwaveWebhookRoute: ApiPublicFlutterwaveWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
